// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOzSbKAwfmtQCQ4FLGVEb8vkK2ljDQpxs',
    appId: '1:478559853980:web:8b4091e2236a5133cc7c59',
    messagingSenderId: '478559853980',
    projectId: 'cardapyia-service-2025',
    authDomain: 'cardapyia-service-2025.firebaseapp.com',
    storageBucket: 'cardapyia-service-2025.firebasestorage.app',
    databaseURL: 'https://cardapyia-service-2025-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6wMn-ci27kDaYfiLiqoe-1G3MDwe5V0',
    appId: '1:478559853980:android:e99a1e14b2d7ebfbcc7c59',
    messagingSenderId: '478559853980',
    projectId: 'cardapyia-service-2025',
    storageBucket: 'cardapyia-service-2025.firebasestorage.app',
    databaseURL: 'https://cardapyia-service-2025-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSTwPlDE5m7uHQvllCtJQBfiT5LX9lMKo',
    appId: '1:478559853980:ios:c28d07067a50d246cc7c59',
    messagingSenderId: '478559853980',
    projectId: 'cardapyia-service-2025',
    storageBucket: 'cardapyia-service-2025.firebasestorage.app',
    iosBundleId: 'com.play101.app',
    databaseURL: 'https://cardapyia-service-2025-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSTwPlDE5m7uHQvllCtJQBfiT5LX9lMKo',
    appId: '1:478559853980:ios:21cdd7837d861e01cc7c59',
    messagingSenderId: '478559853980',
    projectId: 'cardapyia-service-2025',
    storageBucket: 'cardapyia-service-2025.firebasestorage.app',
    iosBundleId: 'com.app.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOzSbKAwfmtQCQ4FLGVEb8vkK2ljDQpxs',
    appId: '1:478559853980:web:52acbcd9c17e54b9cc7c59',
    messagingSenderId: '478559853980',
    projectId: 'cardapyia-service-2025',
    authDomain: 'cardapyia-service-2025.firebaseapp.com',
    storageBucket: 'cardapyia-service-2025.firebasestorage.app',
  );
}
